### ISSUE TITLE
[4.4:68] The system shall provide a notes layout fallback mechanism…

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/sprints#49]
### Requirement

[[4.4:68]](http://snaekobbi.github.io/requirements#4.4:68) The system shall provide a notes layout fallback mechanism that determines the best way to render notes. Notes of a certain type (e.g. footnote or endnote) shall be handled consistently throughout the whole document.
### Tasks
- [ ] CSS support for fallback mechanism: specification (@bertfrees)
- [x] implement (@bertfrees)
- [x] system tests
  - [x] @KariRudjord ![PASS](http://snaekobbi.github.io/sprints/PASS.svg)

**Comment by bertfrees** [comment]
I've moved this to sprint#8 because it has been implemented and I've given Kari an explanation about how to use the feature, so she can include it in her test report if she wishes.

**Comment by bertfrees** [comment]
@stesk said:

> I'm not quite sure what this requirement entails and hence haven't tested it. Also, my input files for these tests have been DTBook files. There is no standardised way of distinguishing footnotes from endnotes in DTBook. At Nota we use class values to mark up <note> elements as footnotes or endnotes, but of course the system doesn't recognise these Nota-specific values at this stage. EPUB files do have separate markup for footnotes and endnotes, so once I understand the requirement, I should be able to test it with EPUB input.

**Comment by bertfrees** [comment]
@stesk What is supported right now is to have notes placed at the bottom of the page by default, and when one or more notes are too big to be rendered at the bottom of the page, to place all notes at the end of the volume or book.

There is a new property called `-obfl-fallback-flow` which should be added to the `@footnotes` rule. Important is that the fallback flow (in this case "endnotes") is consumed somewhere else, in this case in an `@end` rule. Example:

``` css
@page {
  @footnotes {
    content: flow(footnotes);
    -obfl-fallback-flow: endnotes;
  }
}

@volume {
  @end {
    content: flow(endnotes, volume);
  }
}
```

Also important is that notes are sent to the "footnotes" first, for example:

``` css
noteref::alternate {
   flow: footnotes;
   display: block;
   content: target-content(attr(idref));
}
```

It is also possible to increase the maximum allowed space for notes at the bottom of the page. The default is half of the total page height, but you can change that to another value using the `max-height` property. For example:

``` css
@page {
  @footnotes {
    max-height: 15;
  }
}
```

Because the fallback is based on the amount of space the notes take, there is no need to distinguishing footnotes from endnotes in DTBook.
